In [8]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
type(list_)
array_list.dtype

dtype('<U1')

In [10]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("Data types of elements in array_list:")
for element in array_list:
    print(element.dtype)


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<U1
<U1
<U1
<U1
<U1


In [11]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [17]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print("The shape of num_array is:")
print(np.shape(num_array))

print("\n The size of num_array is:")
print(np.size(num_array))

The shape of num_array is:
(2, 3)

 The size of num_array is:
6


In [24]:
import numpy as np
matrix = np.zeros((3,3))
print("Zeros matrix of 3*3 is: \n" , matrix)

Zeros matrix of 3*3 is: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
